#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

npm --version > /dev/null 2> /dev/null
if [ $? -ne 0 ]; then
    echo Install node.js with npm before using this tool.
    exit 1
fi

set -e

if [[ ! -d "$SCRIPT_DIR/package.json" ]]; then
    cat > "$SCRIPT_DIR/package.json" << 'END_OF_TEXT'
<<<PACKAGE>>>
END_OF_TEXT
fi

if [[ ! -d "$SCRIPT_DIR/git2html.mjs" ]]; then
    cat > "$SCRIPT_DIR/git2html.mjs" << 'END_OF_TEXT'
<<<SOURCE>>>
END_OF_TEXT
fi

if [[ ! -d "$SCRIPT_DIR/node_modules/diff2html-cli" ]]; then
    (cd "$SCRIPT_DIR"; npm install)
fi

node "$SCRIPT_DIR/git2html.mjs" "$@"
